<?php
/**
 * Ticket view
 */

?>
<h1>Hantera inbetalningar från OCR</h1>
<?php echo $this->file_form; ?>

<table class="tablesorter">
<thead>
	<tr>
	    <th>Filnamn</th>
	    <th>Tillagd av</th>
	    <th>Tillagd</th>
	    <th>Behandlad</th>
	</tr>
</thead>
<tbody>
<?php
	foreach($this->bankgiroPaymentsFiles as $bankgiroPaymentsFile):
?>
<tr>
    <td>
		<a href=viewOcr?fileId="<?PHP echo $bankgiroPaymentsFile->file_id;?>">
        <?PHP
        	$filenameParts = pathinfo($bankgiroPaymentsFile->filename);
        	if ( isset($filenameParts['extension']) )
        	{
        		echo $filenameParts['filename'].'.'.$filenameParts['extension'];
        	}
        	else
        	{
        		echo $filenameParts['filename'];
        	}

        ?>
        </a>
    </td>
    <td>
    	<?php echo $bankgiroPaymentsFile->username;?>
    </td>
    <td>
        <?php echo $bankgiroPaymentsFile->time_added;?>
    </td>
    <td>
        <?php
        if( 0 != $bankgiroPaymentsFile->treated )
        {
        	echo $bankgiroPaymentsFile->treated;
        }
        else
        {
        	echo '<a href=extract-file?'.$this->queries['extractFile'].'='.$bankgiroPaymentsFile->file_id.' >Behandla</a>';
        }
        ?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>